#!/bin/bash
#SBATCH --job-name=vcfdeg
#SBATCH --output=vcfdeg_%j.o
#SBATCH --error=vcfdeg_%j.e
#SBATCH --account=project_2009301
#SBATCH --partition=small
#SBATCH --time=8:00:00
#SBATCH --ntasks=1
#SBATCH --mem=250G
#SBATCH --mail-type=END
#SBATCH --cpus-per-task=1

module load biokit

DIR=/users/mcevoysu/scratch/output
OUTDIR="$DIR"/site_annotation/Pinusnigra

#bcftools sort -o $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_0fold_1.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_0fold_1.vcf
#bcftools sort -o $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_0fold_2.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_0fold_2.vcf
#bcftools concat -o $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_0fold.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_0fold_1.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_0fold_2.sorted.vcf

#bcftools sort -o $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_1.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_1.vcf
#bcftools sort -o $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_2.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_2.vcf
#bcftools concat -o $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_1.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_2.sorted.vcf

#bcftools sort -o $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_1_1_1.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_1_1_1.vcf
#bcftools sort -o $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_1_1_2.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_1_1_2.vcf
#bcftools sort -o $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_1_2_1.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_1_2_1.vcf
#bcftools sort -o $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_1_2_2.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_1_2_2.vcf
#bcftools sort -o $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_2_1_1.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_2_1_1.vcf
#bcftools sort -o $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_2_1_2.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_2_1_2.vcf
#bcftools sort -o $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_2_2_1.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_2_2_1.vcf
#bcftools sort -o $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_2_2_2.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_2_2_2.vcf
#bcftools concat -o $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_1_1_1.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_1_1_2.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_1_2_1.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_1_2_2.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_2_1_1.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_2_1_2.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_2_2_1.sorted.vcf $OUTDIR/Pinusnigra_SNP_sampleFilt_locimissingness_random_V1_4fold_intergenic_intron_2_2_2.sorted.vcf

TMPDIR=/users/mcevoysu/scratch/output/site_annotation/Pinusnigra/tmp
#bcftools sort -T $TMPDIR -o $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_0fold_1.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_0fold_1.vcf
#bcftools sort -T $TMPDIR -o $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_0fold_2.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_0fold_2.vcf
#bcftools concat -o $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_0fold.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_0fold_1.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_0fold_2.sorted.vcf

bcftools sort -T $TMPDIR -o $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_1.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_1.vcf
bcftools sort -T $TMPDIR -o $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_2.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_2.vcf
bcftools concat -o $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_1.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_2.sorted.vcf

bcftools sort -T $TMPDIR -o $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_1_1_1.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_1_1_1.vcf
bcftools sort -T $TMPDIR -o $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_1_1_2.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_1_1_2.vcf
bcftools sort -T $TMPDIR -o $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_1_2_1.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_1_2_1.vcf
bcftools sort -T $TMPDIR -o $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_1_2_2.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_1_2_2.vcf
bcftools sort -T $TMPDIR -o $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_2_1_1.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_2_1_1.vcf
bcftools sort -T $TMPDIR -o $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_2_1_2.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_2_1_2.vcf
bcftools sort -T $TMPDIR -o $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_2_2_1.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_2_2_1.vcf
bcftools sort -T $TMPDIR -o $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_2_2_2.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_2_2_2.vcf
bcftools concat -o $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_1_1_1.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_1_1_2.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_1_2_1.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_1_2_2.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_2_1_1.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_2_1_2.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_2_2_1.sorted.vcf $OUTDIR/Pinusnigra_SPET_allsites_filt_locimissingness_random_V1_4fold_intergenic_intron_2_2_2.sorted.vcf
